# Generated by Django 4.2.4 on 2023-09-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_infor_buttom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='./upload/produtos')),
                ('title', models.CharField(default='', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
